"use strict";
let memoryData=null,memoryRows=[],memoryArchive=null,memoryRevision=0;
const memoryTab=node('button','人物与回忆');memoryTab.dataset.view='memories';memoryTab.setAttribute('aria-pressed','false');document.querySelector('.views').append(memoryTab);
memoryTab.onclick=()=>document.querySelectorAll('[data-view]').forEach(b=>{b.setAttribute('aria-pressed',String(b===memoryTab));$(b.dataset.view+'-view').hidden=b!==memoryTab;});
function memorySelected(){return memoryRows[Number($("memory-message").value)];}
function memoryItem(m){return memoryData.items.find(x=>x.conversation===m.conversation&&x.message_id===m.id)||{};}
function memoryShow(){const m=memorySelected();if(!m)return;const item=memoryItem(m);$("memory-original").textContent=`[${m.id}] ${m.timestamp} · ${m.sender}\n${m.text}\n附件：${m.media.join('、')||'无'}`;$("memory-tags").value=(item.people||[]).join('，');$("memory-caption").value=item.caption||'';$("memory-transcript").value=item.transcript||item.asr_candidate?.text||'';$("memory-transcript").disabled=m.type!=='audio';$("speech-reference").replaceChildren();for(const ref of m.media)$("speech-reference").append(new Option(ref,ref));$("speech-run").disabled=m.type!=='audio'||!m.media.length;$("speech-candidate").textContent=item.asr_candidate?`待核对 · ${item.asr_candidate.engine} · ${item.asr_candidate.model_name}\n${item.asr_candidate.text}\n\n${item.asr_candidate.segments.map(s=>`${s.start_seconds}–${s.end_seconds}s ${s.text}`).join('\n')}`:'尚无本地识别候选。';}
function memoryRender(data){memoryData=data;$("memory-scope").textContent=`${memoryArchive.label} · ${data.memories.length} 个回忆日 · ${data.people.length} 个人物标签 · 本地注释修订 ${data.revision}`;$("memory-people").replaceChildren();for(const p of data.people){const b=node('button',`${p.name} · ${p.items.length} 条`);b.onclick=()=>memoryDays(new Set(p.items.map(x=>JSON.stringify([x.conversation,x.message_id]))));$("memory-people").append(b);}const all=node('button','全部回忆');all.onclick=()=>memoryDays();$("memory-people").append(all);memoryDays();memoryShow();}
function memoryDays(allowed=null){$("memory-days").replaceChildren();let count=0;for(const day of memoryData.memories){const items=day.items.filter(x=>!allowed||allowed.has(JSON.stringify([x.conversation,x.message_id])));if(!items.length)continue;if(count++>=100)break;const card=node('article',undefined,'rel-card');card.append(node('h3',day.date),node('p',`${items.length} 条 · ${day.date_source}`,'muted'));for(const key of items.slice(0,20)){const index=memoryRows.findIndex(m=>m.conversation===key.conversation&&m.id===key.message_id);if(index<0)continue;const m=memoryRows[index],item=memoryItem(m),button=node('button',`${m.sender} · ${m.type} · ${(item.caption||m.text||m.id).slice(0,60)}`);button.onclick=()=>{$("memory-message").value=String(index);memoryShow();$("memory-original").scrollIntoView({block:'center'});};card.append(button);}if(items.length>20)card.append(node('p','卡片展示前 20 条，完整消息可从下方选择。','muted'));$("memory-days").append(card);}if(count>100)$("memory-days").append(node('p','卡片展示前 100 个回忆日，完整数据保存在备份 annotations.json。','muted'));}
$("memory-refresh").onclick=async()=>{if(!activeArchive){status('请先导入并保存一个档案；虚构示例不自动存档。',true);return;}const archive=activeArchive,rows=[...messages],version=++memoryRevision;try{const data=await api('memories/load',{id:archive.id});if(version!==memoryRevision)return;memoryArchive=archive;memoryRows=rows;$("memory-message").replaceChildren();rows.forEach((m,i)=>$("memory-message").append(new Option(`${m.timestamp} · ${m.sender} · ${m.type} · ${m.id}`,String(i))));memoryRender(data);}catch(e){status(e.message,true);}};
$("memory-message").onchange=memoryShow;
$("memory-save").onclick=async()=>{const m=memorySelected();if(!m||!memoryArchive)return;const id=memoryArchive.id;$("memory-save").disabled=true;try{const data=await api('memories/annotate',{id,conversation:m.conversation,message_id:m.id,people:$("memory-tags").value.split(/[,，]/).map(s=>s.trim()).filter(Boolean),caption:$("memory-caption").value,transcript:m.type==='audio'?$("memory-transcript").value:'',revision:memoryData.revision});if(memoryArchive?.id===id)memoryRender(data);status('人物标签与核对转写已保存，原文未改变。');}catch(e){status(e.message,true);}finally{$("memory-save").disabled=false;}};
$("speech-run").onclick=async()=>{const m=memorySelected();if(!m||!memoryArchive)return;const id=memoryArchive.id;$("speech-run").disabled=true;status('正在本机加载语音模型和识别，首次加载可能较慢，请勿关闭应用…');try{const data=await api('memories/transcribe',{id,conversation:m.conversation,message_id:m.id,media_root:$("speech-root").value,reference:$("speech-reference").value,model_dir:$("speech-model").value});if(memoryArchive?.id===id)memoryRender(data);status('识别候选已保存。请对照原音核对文本，再点击保存已核对转写。');}catch(e){status(e.message,true);}finally{$("speech-run").disabled=false;}};
