"use strict";
let relationship=null, relBusy=false;
const relTab=node("button","情感与关系");relTab.dataset.view="relationship";relTab.setAttribute("aria-pressed","false");
document.querySelector('.views').insertBefore(relTab,document.querySelector('[data-view="ai"]'));
relTab.onclick=()=>{document.querySelectorAll('[data-view]').forEach(b=>{b.setAttribute('aria-pressed',String(b===relTab));$(b.dataset.view+'-view').hidden=b!==relTab;});relConversations();};
const relNames={warmth:"亲近表达",support:"支持表达",distress:"负面感受 / 宣泄",positive:"积极感受",sharing:"分享"};
const eventNames={confession:"表白",conflict:"争执",repair:"道歉 / 修复",commitment:"关系承诺",honeymoon_trip:"蜜月旅行",honeymoon_phase:"热恋阶段",breakup:"分开",other:"其他大事"};
const percent=v=>v===null||v===undefined?"无可用样本":`${v}%`;
const seconds=v=>v===null?"无可用样本":v<60?`${v} 秒`:`${(v/60).toFixed(1)} 分钟`;
function relConversations(){const current=$("rel-conversation").value;$("rel-conversation").replaceChildren(new Option("选择一对一会话",""));for(const name of new Set(messages.map(m=>m.conversation)))$("rel-conversation").append(new Option(name,name));$("rel-conversation").value=current||selected.conversation||($("rel-conversation").options.length===2?$("rel-conversation").options[1].value:"");}
async function relRefresh(){const r=await api("relationship/list",{});$("rel-saved").replaceChildren(new Option("选择已保存报告",""));for(const item of r.reports)$("rel-saved").append(new Option(`${item.conversation} · ${item.scope.from.slice(0,10)} — ${item.scope.to.slice(0,10)} · ${item.scope.messages} 条`,item.id));$("rel-saved").value=relationship?.id||"";}
function relEvidence(ids){const box=node("details"), rows=new Map(relationship.messages.map(m=>[m.id,m]));box.append(node("summary",`查看证据（${ids.length} 条）`));for(const id of ids){const m=rows.get(id);if(m)box.append(node("pre",`[${m.id}] ${m.timestamp} · ${m.sender}\n${m.text||'['+m.type+']'}`,"rel-evidence"));}return box;}
function relRender(r){
  relationship=r;$("rel-result").hidden=false;$("rel-scope").textContent=`已存本机 · ${r.settings.conversation} · ${r.scope.from} — ${r.scope.to} · ${r.scope.messages} 条 · ${r.method} · 报告时区 UTC${r.settings.utc_offset>=0?'+':''}${r.settings.utc_offset} / 间隔 ${r.settings.gap_hours} 小时 / ${r.settings.quiet?'排除夜间':'包含夜间'}。上方设置仅在重新生成时生效。`;
  $("rel-profiles").replaceChildren();
  for(const p of r.profiles){const card=node("article",undefined,"rel-card");card.append(node("p",`${p.person} → ${p.toward}`,"eyebrow"),node("h3","互动投入指数"),node("strong",p.interaction_index===null?"—":`${p.interaction_index} / 100`,"rel-score"),node("p",p.index_status,"muted"));
    for(const [key,label] of [['continuation','窗口内接续率 · 50%'],['initiative','新会话发起份额 · 30%'],['sharing','本人分享轮次率 · 20%']]){const v=p.components[key],line=node('div',undefined,'rel-dimension'),bar=node('meter');bar.min=0;bar.max=100;bar.value=v??0;bar.setAttribute('aria-label',label);line.append(node('span',`${label}：${percent(v)}`),bar);card.append(line);}
    const c=p.counts,d=p.reply_seconds;card.append(node('p',`${c.messages} 条 / ${c.turns} 轮 · ${p.active_days} 活跃日 · 消息占比 ${percent(p.message_share)}\n发起 ${c.initiations||0} 次 · 接续 ${c.responses||0} / ${c.opportunities||0} 次机会 · 排除 ${c.excluded_opportunities||0} 次\n回复中位 ${seconds(d.median)}（n=${d.n}）；四分位 ${seconds(d.q1)} — ${seconds(d.q3)}\n含夜间中位 ${seconds(d.raw_median)}（n=${d.raw_n}）`,'rel-facts'));
    card.append(node('h3','可观察沟通画像'));
    for(const [key,label] of Object.entries(relNames)){card.append(node('p',`${label}线索：${c[key]||0} 条 / ${c.messages} 条`));if(p.evidence[key]?.length)card.append(relEvidence(p.evidence[key]));}
    card.append(node('p',`对方披露情绪后的相邻回应 ${c.disclosure_responses||0} 轮，其中支持词线索 ${c.support_after_disclosure||0} 轮（需阅读语境）。`,'muted'));
    if(p.reply_evidence.length){const e=node('details');e.append(node('summary','回复时延计算证据（最多 20 对）'));for(const pair of p.reply_evidence){e.append(node('p',`${pair.from_id} → ${pair.to_id}：${seconds(pair.seconds)}`),relEvidence([pair.from_id,pair.to_id]));}card.append(e);}$("rel-profiles").append(card);
  }
  $("rel-method").replaceChildren();for(const text of r.limitations)$("rel-method").append(node('p',text,'muted'));for(const s of r.sources)$("rel-method").append(node('p',`${s.title}\n${s.url}`,'muted'));
  const table=node('table'),head=node('tr');for(const label of ['月份','发言者','消息','亲近线索','支持线索','宣泄线索','积极线索'])head.append(node('th',label));table.append(head);for(const month of r.monthly)for(const [person,c] of Object.entries(month.people)){const tr=node('tr');for(const value of [month.month,person,c.messages||0,...['warmth','support','distress','positive'].map(k=>c.messages?`${c[k]||0} · ${(100*(c[k]||0)/c.messages).toFixed(1)}%`:'—')])tr.append(node('td',value));table.append(tr);}$("rel-monthly").replaceChildren(table);
  $("rel-events").replaceChildren();$("rel-event-count").textContent=`检测到 ${r.candidate_count} 条关键词候选，最多保留前 200 条供核对；已确认 ${r.events.filter(e=>e.status==='confirmed').length} 条。候选的提及日期不等于事件日期。`;
  for(const e of r.events){const item=node('details',undefined,'rel-event');item.append(node('summary',`${e.status==='confirmed'?'已确认':e.status==='dismissed'?'已排除':'待核实'} · ${e.date||e.mentioned_on||'未填日期'} · ${e.title}`));item.append(node('p',`提及日期：${e.mentioned_on||'手动添加'}；实际日期由你确认。`,'muted'),relEvidence(e.evidence_ids),relEventForm(e));$("rel-events").append(item);}
  $("rel-ai-output").textContent=r.ai||"尚未生成。";
}
function relEventForm(event={}){const form=node('form',undefined,'rel-event-form'),controls={};for(const [key,label,type] of [['kind','类型','select'],['title','标题','text'],['date','实际日期','date'],['end_date','阶段结束（可选）','date'],['status','状态','select'],['note','备注','text']]){const wrap=node('label',label),input=node(type==='select'?'select':'input');if(type!=='select')input.type=type;if(key==='kind')for(const [v,t] of Object.entries(eventNames))input.append(new Option(t,v));if(key==='status')for(const [v,t] of [['candidate','待核实'],['confirmed','已确认'],['dismissed','已排除']])input.append(new Option(t,v));input.value=event[key]||(key==='kind'?'other':key==='status'?'candidate':'');if(key==='title')input.maxLength=200;if(key==='note')input.maxLength=2000;wrap.append(input);form.append(wrap);controls[key]=input;}
  const button=node('button','保存节点','primary');button.type='submit';form.append(button);form.onsubmit=async ev=>{ev.preventDefault();const id=relationship.id,payload={id:event.id||'',...Object.fromEntries(Object.entries(controls).map(([k,v])=>[k,v.value]))};button.disabled=true;try{const r=await api('relationship/event',{id,event:payload});if(relationship?.id===id)relRender(r);status('大事节点已保存在本机。');}catch(e){status(e.message,true);}finally{button.disabled=false;}};return form;
}
$("rel-add").onclick=()=>{const item=node('details',undefined,'rel-event');item.open=true;item.append(node('summary','新建节点'),relEventForm());$("rel-events").prepend(item);};
$("rel-build").onclick=async()=>{if(relBusy)return;if($("rel-transcripts").checked&&!activeArchive){status('纳入转写需要先打开已保存档案。',true);return;}relBusy=true;$("rel-build").disabled=true;try{const r=await api('relationship/build',{messages,archive_id:activeArchive?.id,include_transcripts:$("rel-transcripts").checked,conversation:$("rel-conversation").value,start:$("rel-start").value,end:$("rel-end").value,gap_hours:Number($("rel-gap").value),quiet:$("rel-quiet").checked,utc_offset:Number($("rel-zone").value)});relRender(r);await relRefresh();status('关系报告已保存本机。请核对情感线索和大事候选。');}catch(e){status(e.message,true);}finally{relBusy=false;$("rel-build").disabled=false;}};
$("rel-refresh").onclick=()=>{relConversations();relRefresh().catch(e=>status(e.message,true));};
let relLoad=0;$("rel-saved").onchange=async()=>{const id=$("rel-saved").value,version=++relLoad;if(!id)return;try{const r=await api('relationship/load',{id});if(version===relLoad)relRender(r);}catch(e){status(e.message,true);}};
document.querySelectorAll('[data-rel-export]').forEach(b=>b.onclick=async()=>{if(!relationship)return;try{const fmt=b.dataset.relExport,r=await api('relationship/export',{id:relationship.id,format:fmt});download(r.content,`relationship-${relationship.id.slice(0,10)}.${fmt==='markdown'?'md':fmt}`,fmt==='ics'?'text/calendar':'text/plain');}catch(e){status(e.message,true);}});
$("rel-ai").onclick=async()=>{if(!relationship)return;const id=relationship.id,cloud=$("provider").value==='deepseek',key=$("api-key").value.trim();if(cloud&&!key&&!savedKey){status('请在 AI 分析页填写或保存 Key。',true);return;}if(cloud&&!window.confirm(`将报告范围的 ${relationship.scope.messages} 条消息正文、时间、姓名和 ID 发送至 api.deepseek.com，可能产生费用。确认？`))return;const payload={id,provider:$("provider").value,model:$("model").value,consent:cloud,api_key:key,use_saved_key:!key&&savedKey};$("rel-ai").disabled=true;if(cloud)$("api-key").value='';try{const pending=api('relationship/analyze',payload);delete payload.api_key;const r=await pending;if(relationship?.id===id)relRender(r);status('AI 解读已保存本机；请核对引文，结果不会自动确认为大事。');}catch(e){status(e.message,true);}finally{delete payload.api_key;$("rel-ai").disabled=false;}};
relRefresh().catch(e=>status(e.message,true));
